provider: litellm
anthropic:
  api_key: ""
  model: claude-sonnet-4-5-20250929
openai:
  api_key: ""
  model: gpt-4o
ollama:
  model: 'qwen3:4b'
  url: http://localhost:11434/v1
litellm:
  api_key: ""
  model: gemini-3.6-flash
  url: https://litellm.wibrow.dev
